package models

//{
//"client_id":"08887",
//"prefix":"8",
//"data":"G0hIGUwhHRwYEkQNAkZYVlxWAktYdHtUdUoBChwzCmBbVXZNdFFUF0VQAzQMBVdVYEZ-SghPODBiN0QaEkNDFxRGQBRCGBgZEwNCNEREV0hcUAJLRXoOV31TekwESzQaE0dCDUQZFRkYAUdDGhUVHRkfNxIIeAJQeU8JR0t1NCIFRUEQNRQKTFdUCgFNSFVCWE8EVEs3UAlEGUYaFUJEGxRHRAI_CkteVVUFf0VVQlFJVHoIIDdjWUIBbQoOMwZhU3ozGjVLWk5DVXtUSU9PTFZONxIIC39ZCFZ2VEFydUtSCn9UNSIKIRIRR0IQExMTGBdFFhZFRwlAAwlaWnBzVVIKf1Q1IgoaEhFGQhAFDwVKUAFSTwN9RghaBU0ESzRLBRI"
//}

type Content struct {
	ClientID string `json:"client_id"`
	Prefix string `json:"prefix"`
	Data string `json:"data"`
}